name: article_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project with Serverpod.
environment: 
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies: 
  serverpod_flutter: ^0.9.21
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  article_client: 
    path: ../article_client

dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

